### ISSUE TITLE
`resource_name_exists?': wrong number of arguments (given 1, expected 0) (ArgumentError)

### ISSUE THREAD

**Issue by audioe** [GorillaStack/retro-tag#17]
Getting the below error when running retro_tag.rb

```
Completed collecting resources in 44 seconds
Found 1,211 total events to process, looking for events with existing resources...
( ●    ) 1,211 events selected to be processed.../home/ubuntu/environment/retro-tag/aws_resource/security_group.rb:38:in `resource_name_exists?': wrong number of arguments (given 1, expected 0) (ArgumentError)
        from /home/ubuntu/environment/retro-tag/aws_resource/default.rb:117:in `process_cloudtrail_event'
        from ./retro_tag.rb:202:in `block in <main>'
        from /home/ubuntu/.rbenv/versions/3.0.6/lib/ruby/3.0.0/csv/table.rb:539:in `each'
        from /home/ubuntu/.rbenv/versions/3.0.6/lib/ruby/3.0.0/csv/table.rb:539:in `each'
        from ./retro_tag.rb:190:in `<main>'
```

This is when trying to run it in a single account, so CF stacks are deployed here, and just wanting to retro-tag resources in this same account.  I'm running the following after exporting the relevant CSV paths/buckets/etc.  For SCAN_PROFILE and LAMBDA_PROFILE, i'm using the same aws configure profile

```
./retro_tag.rb \
  --csv "$CSV_PATH" \
  --bucket $BUCKET \
  --bucket-region $BUCKET_REGION \
  --scan-profile "$SCAN_PROFILE" \
  --lambda-profile "$LAMBDA_PROFILE" \
  --lambda-region $LAMBDA_REGION
```

**Comment by audioe** [comment]
I've managed to fix this by changing the following lines in the following files:

line 117 & 118 in default.rb
from:
```
        if resource_name_exists?(options)
          event_resource_name = resource_name(options)
```
to
```
        if resource_name_exists?(**options)
          event_resource_name = resource_name(**options)
```

Lines 39 & 43 in cw_alarm.rb
from:
`(arn_builder(args))`
to
`(arn_builder(**args))`
